config/routes.rb
 Rails.application.routes.draw do
  resources :clients

  get 'pages/home'

  get 'pages/what'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/blog'

  root 'pages#home'

  post 'pages/thank_you'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :mail, :skype, :gender)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def what
  end

  def about
  end

  def contact
  end

  def blog
  end

def thank_you
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  UserMailer.contact_form(@email, @name, @message).deliver
end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :skype %><br>
    <%= f.text_field :skype %>
  </div>
    <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Skype</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.mail %></td>
        <td><%= client.skype %></td>
        <td><%= client.gender %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @client.mail %>
</p>

<p>
  <strong>Skype:</strong>
  <%= @client.skype %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @client.gender %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag 'application' %>
    
  <%= csrf_meta_tags %>

<link href='http://fonts.googleapis.com/css?family=Cantata+One' rel='stylesheet' type='text/css'>

  <title>Coaching - Melotos</title>

</head>
  
<body>
 <div class="navbar navbar-inverse navbar-fixed-top">

<footer>
    <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <div class="container">
        <div class="navbar-header">
        <a href="pages/home.html" rel="home" title="Melanie Goebl"><img src="../../img/melotos-02.png" style="width:183px;height:50px" alt="Melanie Goebl" id="logo" /></a>
          </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
            <%= link_to 'Home', pages_home_path %>
            </div>
            <div class="form-group">
            <%= link_to 'Approach', pages_what_path %>
            </div>
            <div class="form-group">
            <%= link_to 'About', pages_about_path %>
            </div>
            <div class="form-group">
            <%= link_to 'Blog', pages_blog_path %>
            <div class="form-group">
            <%= link_to 'Contact', pages_contact_path %>
            </div>
          </form>
        </div>
      </div>
    </div>
</form>
</div>
</div>
</div>
</footer>


<%= yield %>


</body>

</html>

app/views/pages/about.html.erb
<div class="topimage" >
<a> ABOUT MYSELF </a>
</div>

<div class="container about">
<div class="row">
  <div class="carton">
  	“You never change things by fighting the existing reality.
	To change something, build a new model that makes the existing model obsolete.”
	<br><br>
	― Buckminster Fuller
  </div>
  <div class="col-md-4">
	<br><br><br><br><br>
	<img src="../../img/mel.jpg" alt="Transformation" style="width:400px;height:500px">  
		<br><br><br><br><br><br><br><br><br><br>
  </div>
  <div class="col-md-4">
    <br><br><br><br>
    <p> I grew up on a farm in the Black Forest, Germany.
        <br><br>
		In her teens she moved to boarding school, where alcohol and drugs became part of her life. At that time she had the chance to travel to Egypt and India, which started her interest in different cultures and food. Later traveling in Asia and Australia she decided to study art, which seemed fitting for a free spirit like her. But although making art and traveling around the world where amazing learning experiences, she felt lost and became depressed and very sick. 
        <br><br>
		In 2009 while traveling in Argentina a Gastroenteritis led to Arthritis and she was told, that she'll never be able to walk normal again. After this diagnosis she started researching and became a raw vegan in a matter of days and soon found herself working at the Farm of Life in Costa Rica. While fasting and feasting, cleansing and mediating and eating mostly raw she has overcome many ailments like depression, joint pain and lost weight along the way. 
		A more detailed biography can be found here.
		Over the past 3 years Melanie has been working at the Restaurant La Mano Verde and Veganz in Berlin as well as the Cafe Gratitude in Munich. Currently she works as a private Chef and is a student at the Institute for Integrative Nutrition.
		Melanie's raw food healing journey can be experienced through her blog. - See more at: http://www.melanielotos.com/about-
		</p>
		<br><br><br><br><br><br><br><br>
   </div>
</div>
</div>
</div>

app/views/pages/contact.html.erb
<div class="contact">
<h1 >  any questions? get in touch: </h1>
</div>

<%= flash[:notice] %>

<%= form_tag("/pages/thank_you") do %>
<div class="row">
	<div class="contact col-md-4">
	<div class="form-group">
			<%= label_tag :name, "Name" %>
	    <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
		</div>		
		<div class="form-group">
			<%= label_tag :email, "Email Address" %>
			<%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
		</div>
		<div class="form-group">
			<%= label_tag :message, "Message" %>
			<%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
		</div>		
	</div>
</div> 
<%= submit_tag "Send" %>   
<% end %>

app/views/pages/home.html.erb
<script>
 $(function() {
  var BV = new $.BigVideo();
  BV.init();
  BV.show('../../video/smoothie.mp4',{ambient:true});
});
</script>


<div class= "bgimage" >
<div class="container">
<div class="row">
<div class="col-sm-3 col-md-3">
    <h1> READY <br>
    FOR <br>
    CHANGE? </h1>
    <h2> ___________ </h2>
</div>
<div class="col-sm-3 col-md-3">
    <p> Learn how to: <br><br>
    + over come chronic pain  &  gain back energy <br>
    + develop and maintain healthy eating habits <br>
    + change your mindset <br>
    + feel good about yourself! <br>
    </p>
    <p>= reach your goals and live the life you want!</p>
</div>
</div>
</div>
</div>

app/views/pages/thank_you.html.erb
<div class="row">
  <div class="col-md-4 thank">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div>
</div>

app/views/pages/what.html.erb
<link rel="stylesheet" type="text/css" href="coverflow.css" />
<script src="jquery.min.js"></script>


			<div class="row">
				<div class="col-md-12 ui-coverflow-wrapper ui-clearfix">
		<div class="wrapper ui-coverflow" id="coverflow">
			<img
				src="../../img/.jpg"
				alt="The Prodigy - music for the jilted generation" />
			<img
				src="../../img/.jpg"
				alt="Nana Kitade - I scream"
				data-license="http://creativecommons.org/licenses/by/2.0/"
				data-contact="http://www.flickr.com/photos/puuikibeach/"
				data-author="davidd" />
			
		</div>
		<div id="license">
		</div>
	</div>
	</div>



<script src="coverflow.min.js"></script>
<script>
    $(function() {
		// and kick off
        $('#coverflow').coverflow();
    });
</script>